server:
  port: 8080
management:
  security:
    enabled: false
spring:
  application:
    name: spring-boot-h2-db-web-app
  datasource:
    url: jdbc:oracle:thin://database_host_name:1521/db_sid
    username: ROOT
    password: ROOT
  jpa:
    show-sql: true
